### ISSUE TITLE
Montagem final - Integração entre módulos e interface do usuário

### ISSUE THREAD

**Issue by pedrolopescps** [kevinmmartins/MyQuarium#9]
Montagem final do sistema para efeito de teste, onde serão integrados os módulos de comunicação, de controle, e será testada a interface entre o módulo de controle e o servidor de gerência.

**Comment by pedrolopescps** [comment]
Necessária a integração da parte de comunicação com o servidor dentro do sistCtrl

**Comment by kevinmmartins** [comment]
@Gustavocirulo A estrutura proposta para o json será respeitada  ?

**Comment by kevinmmartins** [comment]
Realizada a comunicação da aplicação com o módulo integrador

**Comment by kevinmmartins** [comment]
Integração completa
